services:
  api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - main
    environment:
      - APP_VERSION=0.0.1
      
      - POSTGRES_USER=bubble-user
      - POSTGRES_PASSWORD=zaq1@WSX
      - POSTGRES_DB=bubble-pop-dev
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  db:
    image: postgres:17.2
    networks:
      - main
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bubble-user
      - POSTGRES_PASSWORD=zaq1@WSX
      - POSTGRES_DB=bubble-pop-dev
      - POSTGRES_PORT=5432
    volumes:
      - ./src/data/dump.sql:/docker-entrypoint-initdb.d/dump.sql

networks:
  main:
    driver: main
